### ISSUE TITLE
lib/key: signatures and recovery

### ISSUE THREAD

**Issue by q9f** [q9f/eth.rb#15]
implement sign and verify for keys. 

- [x] sign
- [x] verify
- [x] personal_sign (eip 191) #24 
- [x] personal_recover (eip 191) #21 
- [x] typed structered data signing (eip 712) #27
